# Generated by Django 3.0.8 on 2020-11-01 17:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 11, 1)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 700416, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 700443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 703380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 703647, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 704798, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 704390, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 704434, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 704369, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competitionpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 705088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 11, 1)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 11, 1)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 700779, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 699997, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_activity_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 699866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 701986, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 11, 1)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 11, 1)),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 702708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 702727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 701427, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 703994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 17, 31, 4, 702389, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='HobbyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('loves', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('communities_involved', models.IntegerField(default=0)),
                ('competition_participated', models.IntegerField(default=0)),
                ('competition_hosted', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobby_report_account', to=settings.AUTH_USER_MODEL)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobby_report_hobby', to='insight.Hobby')),
            ],
        ),
    ]
