# Generated by Django 3.0.5 on 2020-11-02 17:26

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc
import djongo.models.fields
import insight.models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_auto_20201101_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=10)),
                ('created_at', models.DateField()),
                ('searched_text', djongo.models.fields.ArrayField(model_container=insight.models.TextData)),
                ('coordinates', djongo.models.fields.ArrayField(model_container=insight.models.CoordinatesData)),
                ('headers', djongo.models.fields.ArrayField(model_container=insight.models.JsonData)),
                ('logs', djongo.models.fields.ArrayField(model_container=insight.models.TextData)),
                ('process', djongo.models.fields.ArrayField(model_container=insight.models.TextData)),
            ],
            options={
                'required_db_vendor': 'insight_story',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HobbyNearest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_primary_hobby', models.TextField()),
                ('chosen_hobby', models.TextField()),
                ('source', models.TextField()),
                ('is_recommended', models.BooleanField(default=False)),
            ],
            options={
                'required_db_vendor': 'insight_story',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RankReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('rank', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=4, max_digits=8)),
                ('total_pax', models.IntegerField()),
            ],
            options={
                'required_db_vendor': 'insight_story',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='country_code',
            field=models.CharField(default='+91', max_length=4),
        ),
        migrations.AddField(
            model_name='hobbyreport',
            name='posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 11, 2)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 567936, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 567963, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 570845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 571117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 572271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 571863, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 571905, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 571843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competitionpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 572558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 11, 2)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 11, 2)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 568309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 567510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_activity_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 567369, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 569423, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 11, 2)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 11, 2)),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 570164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 570184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 568906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 571467, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 26, 5, 569820, tzinfo=utc)),
        ),
    ]
