# Generated by Django 3.0.5 on 2020-11-05 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0003_auto_20201102_1726'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='datalog',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='hobbynearest',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='rankreport',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='datalog',
            name='user_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 11, 5)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 876532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 876560, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 880114, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 880327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 881551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 881137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 881177, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 881119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competitionpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 881837, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 11, 5)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 11, 5)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 877049, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 876051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_activity_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 875914, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 878585, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='user_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 11, 5)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 11, 5)),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 879422, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 879442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 877997, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 880677, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 16, 17, 38, 879096, tzinfo=utc)),
        ),
    ]
