# Generated by Django 3.0.5 on 2020-11-06 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004_auto_20201105_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='loves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 11, 6)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 269378, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 269406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 272379, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 272632, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 273876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 273457, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 273498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 273437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competitionpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 274174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 11, 6)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 11, 6)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 269751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 268884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_activity_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 268748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 270825, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 11, 6)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 11, 6)),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 271623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 271642, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 270365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 272990, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 59, 51, 271292, tzinfo=utc)),
        ),
    ]
