# Generated by Django 3.0.8 on 2020-08-13 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004_auto_20200804_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, default='', max_length=50)),
                ('post_id', models.CharField(db_index=True, default='', max_length=15)),
                ('loved', models.BooleanField(default=False)),
                ('loved_at', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 11, 35, 0, 210611, tzinfo=utc))),
                ('viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateField(default=datetime.datetime(2020, 8, 13, 11, 35, 0, 210746, tzinfo=utc))),
                ('shared', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('commented', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 8, 13)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 8, 13)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 8, 13)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 11, 35, 0, 212307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 11, 35, 0, 206313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 11, 35, 0, 216586, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractionref',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 8, 13)),
        ),
        migrations.AlterField(
            model_name='useractionref',
            name='time_created',
            field=models.TimeField(default=datetime.time(17, 5, 0, 208182)),
        ),
    ]
