# Generated by Django 3.0.5 on 2020-11-17 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0005_auto_20201106_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='last_scoreboard',
            field=models.DateField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 838641, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='original_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 842537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 11, 17)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 839999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 840026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 843007, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 843292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 844567, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 844157, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 844201, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 844137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competitionpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 844852, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 11, 17)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 11, 17)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 840369, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 839508, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_activity_on',
            field=models.DateField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 839380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 841424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 11, 17)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 11, 17)),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 842213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 842233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 840965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 843693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 40, 49, 841898, tzinfo=utc)),
        ),
    ]
