# Generated by Django 3.0.5 on 2020-11-18 05:36

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0006_auto_20201117_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='coords',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='coords',
            new_name='coordinates',
        ),
        migrations.RemoveField(
            model_name='account',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='account',
            name='friend_count',
        ),
        migrations.RemoveField(
            model_name='account',
            name='friend_requests',
        ),
        migrations.RemoveField(
            model_name='account',
            name='influencer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='influencing_hobby',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saves',
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_activity_on',
        ),
        migrations.AddField(
            model_name='post',
            name='a_tags',
            field=models.ManyToManyField(blank=True, default='', related_name='a_tags_post', to='insight.Tags'),
        ),
        migrations.AddField(
            model_name='post',
            name='down_votes',
            field=models.ManyToManyField(blank=True, default='', related_name='down_votes_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='freshness_score',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='post',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, default='', related_name='hash_tags_post', to='insight.Tags'),
        ),
        migrations.AddField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 960928, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='loves',
            field=models.ManyToManyField(blank=True, default='', related_name='loves_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='net_score',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.ManyToManyField(blank=True, default='', related_name='shares_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='up_votes',
            field=models.ManyToManyField(blank=True, default='', related_name='up_votes_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, default='', related_name='views_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_type',
            field=models.CharField(default='HASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 11, 18)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 966800, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 966887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 970596, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 970964, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 972989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 972304, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 972378, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 972272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competitionpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 973588, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='last_scoreboard',
            field=models.DateField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 958664, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 967558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 960970, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 11, 18)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 11, 18)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='original_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 969704, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 969165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 969201, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 959865, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 971630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 5, 36, 48, 968631, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='RankBadge',
        ),
    ]
