# Generated by Django 3.0.5 on 2020-11-19 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0007_auto_20201118_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreboard',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='hobby_scores',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='loves',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='up_votes',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, default='', related_name='comments_post', to='insight.UserPostComment'),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='posts',
            field=models.ManyToManyField(blank=True, default='', related_name='scoreboard_posts', to='insight.Post'),
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 11, 19)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 774689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 774760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 778317, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 778702, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 780937, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 780010, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 780269, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 779975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competitionpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 781443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='last_scoreboard',
            field=models.DateField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 765524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 775411, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 768459, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 768416, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 11, 19)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 11, 19)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='original_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 776769, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 766686, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 779315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 3, 44, 767149, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ScorePost',
        ),
    ]
