# Generated by Django 3.0.5 on 2020-11-20 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0008_auto_20201119_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreboard',
            name='net_score',
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 11, 21)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 423946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 423979, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 425814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 426034, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 427260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 426777, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 426822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 426757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competitionpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 427554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='last_scoreboard',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 418973, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 424327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 420519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 420499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 11, 21)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 11, 21)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='original_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 424983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 419584, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='assigned_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 426377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 18, 44, 54, 419840, tzinfo=utc)),
        ),
    ]
