# Generated by Django 3.0.5 on 2020-11-22 04:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0009_auto_20201120_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymember',
            name='account',
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='community',
        ),
        migrations.RemoveField(
            model_name='competitionpost',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='competitionpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='to',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='account',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='community',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='last_scoreboard',
        ),
        migrations.RemoveField(
            model_name='post',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 11, 22)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 4, 59, 39, 923795, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 4, 59, 39, 923834, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 4, 59, 39, 920007, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 4, 59, 39, 919986, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 11, 22)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 11, 22)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='original_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 4, 59, 39, 924529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 4, 59, 39, 919021, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 4, 59, 39, 919305, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='CommunityMember',
        ),
        migrations.DeleteModel(
            name='CommunityPost',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='CompetitionPost',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
