# Generated by Django 3.0.8 on 2020-08-16 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0009_auto_20200816_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 15, 23, 55, 136260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateField(default=datetime.datetime(2020, 8, 16, 15, 23, 55, 136489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 15, 23, 55, 139332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 15, 23, 55, 128937, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default='', max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 15, 23, 55, 145739, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractionref',
            name='time_created',
            field=models.TimeField(default=datetime.time(20, 53, 55, 131804)),
        ),
    ]
