# Generated by Django 3.0.5 on 2020-11-30 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0010_auto_20201122_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='loves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 11, 30)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 9, 53, 48, 423484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 9, 53, 48, 423517, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 9, 53, 48, 420081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 9, 53, 48, 420061, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 11, 30)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 11, 30)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='original_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 9, 53, 48, 424137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 9, 53, 48, 419137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 9, 53, 48, 419418, tzinfo=utc)),
        ),
    ]
