# Generated by Django 3.0.5 on 2020-12-21 13:33

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import djongo.models.fields
import insight.models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0011_auto_20201130_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightPostDownVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'insight_post_down_votes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsightPostUpVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'insight_post_up_votes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsightPostViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'insight_post_views',
                'managed': False,
            },
        ),

    ]
