# Generated by Django 3.0.8 on 2020-08-16 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0012_auto_20200816_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 21, 49, 27, 204149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='post_id',
            field=models.CharField(db_index=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateField(default=datetime.datetime(2020, 8, 16, 21, 49, 27, 204297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 21, 49, 27, 205822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 21, 49, 27, 199806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 21, 49, 27, 211306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractionref',
            name='time_created',
            field=models.TimeField(default=datetime.time(3, 19, 27, 201642)),
        ),
    ]
