# Generated by Django 3.0.5 on 2020-12-25 18:04

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0015_auto_20201221_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='rankreport',
            name='total_pax',
        ),
        migrations.RemoveField(
            model_name='rankreport',
            name='user_id',
        ),
        migrations.AddField(
            model_name='post',
            name='alive_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 4, 35, 558962, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='rankreport',
            name='result_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rankreport',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='competition_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 12, 25)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 4, 35, 565794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 4, 35, 565811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 4, 35, 565772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 4, 35, 559011, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_validity',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 4, 35, 558885, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='alive_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 4, 35, 567217, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 4, 35, 567149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='current_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 4, 35, 567236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='tree',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 12, 25)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 12, 25)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='original_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 4, 35, 564876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 4, 35, 556778, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 18, 4, 35, 557075, tzinfo=utc)),
        ),
    ]
