# Generated by Django 3.0.5 on 2020-12-27 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import djongo.models.fields
import insight.models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0016_auto_20201225_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalog',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='datalog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='datalog',
            name='log_type',
        ),
        migrations.RemoveField(
            model_name='datalog',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='datalog',
            name='searched_text',
        ),
        migrations.AddField(
            model_name='datalog',
            name='body',
            field=djongo.models.fields.ArrayField(default=list, model_container=insight.models.JsonData),
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 12, 27)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 818433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 818449, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 818412, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 820682, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='headers',
            field=djongo.models.fields.ArrayField(default=list, model_container=insight.models.JsonData),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='process',
            field=djongo.models.fields.ArrayField(default=list, model_container=insight.models.TextData),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='user_id',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='alive_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 813408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 813425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_validity',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 813385, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='alive_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 819872, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 819805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 819890, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 12, 27)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 12, 27)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='original_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 817571, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 812393, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 16, 13, 2, 812745, tzinfo=utc)),
        ),
    ]
