# Generated by Django 3.0.5 on 2020-12-27 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0018_auto_20201227_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 513154, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 513172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 513133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 515412, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='alive_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 508447, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 508463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_validity',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 508426, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='alive_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 514524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 514461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 514543, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='original_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 512331, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 507551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 2, 30, 507851, tzinfo=utc)),
        ),
    ]
