# Generated by Django 3.0.5 on 2021-01-07 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0019_auto_20201227_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2021, 1, 7)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 457173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 457191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 457152, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 459439, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='alive_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 452434, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 452449, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_validity',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 452413, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='alive_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 458543, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 458480, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 458560, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 1, 7)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2021, 1, 7)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='original_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 456362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 451530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 14, 22, 5, 451833, tzinfo=utc)),
        ),
    ]
