# Generated by Django 3.0.5 on 2021-01-23 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import djongo.models.fields
import insight.models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0020_auto_20210107_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('account_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('notifications', djongo.models.fields.ArrayField(model_container=insight.models.NotificationBody)),
                ('anyNew', models.BooleanField(default=False)),
            ],
            options={
                'required_db_vendor': 'insight_story',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2021, 1, 23)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 530421, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 530447, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 530385, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 534214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='alive_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 522641, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 522670, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_validity',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 522604, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='alive_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 532747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 532638, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankreport',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 532775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 1, 23)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2021, 1, 23)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='original_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 529056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 521121, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 54, 55, 521632, tzinfo=utc)),
        ),
    ]
