# Generated by Django 3.0.8 on 2020-09-04 08:59

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import insight.utils


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0021_auto_20200901_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('tag', models.CharField(default='', max_length=50,
                                         primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(
                    2020, 9, 4, 8, 59, 35, 851647, tzinfo=utc))),
                ('description', models.TextField()),
                ('avatar', models.TextField()),
                ('banner', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='places',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 9, 4)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(
                2020, 9, 4, 8, 59, 35, 837765, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(
                2020, 9, 4, 8, 59, 35, 837904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 9, 4)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 9, 4)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(
                2020, 9, 4, 8, 59, 35, 839494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(
                2020, 9, 4, 8, 59, 35, 833429, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='date_field',
            field=models.DateField(default=datetime.date(2020, 9, 4)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='time_field',
            field=models.TimeField(default=datetime.time(14, 29, 35, 845861)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(
                2020, 9, 4, 8, 59, 35, 843464, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractionref',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 9, 4)),
        ),
        migrations.AlterField(
            model_name='useractionref',
            name='time_created',
            field=models.TimeField(default=datetime.time(14, 29, 35, 835586)),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(
                    2020, 9, 4, 8, 59, 35, 848013, tzinfo=utc))),
                ('team_id', models.CharField(default='tag',
                                             max_length=50, primary_key=True, serialize=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='teamcreator', to=settings.AUTH_USER_MODEL)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='head', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('com_id', models.CharField(default='comp_id',
                                            max_length=50, primary_key=True, serialize=False)),
                ('tag', models.CharField(default='', max_length=20, unique=True)),
                ('start_at', models.DateTimeField(default=datetime.datetime(
                    2020, 9, 4, 8, 59, 35, 856925, tzinfo=utc))),
                ('end_at', models.DateTimeField(default=datetime.datetime(
                    2020, 9, 4, 8, 59, 35, 857023, tzinfo=utc))),
                ('result_at', models.DateTimeField(default=insight.utils.get_ist)),
                ('description', models.TextField()),
                ('avatar', models.TextField()),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                                related_name='community', to='insight.Community')),
                ('hobbies', models.ManyToManyField(to='insight.Hobby')),
                ('places', models.ManyToManyField(to='insight.Places')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='communitycreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='hobbies',
            field=models.ManyToManyField(to='insight.Hobby'),
        ),
        migrations.AddField(
            model_name='community',
            name='places',
            field=models.ManyToManyField(to='insight.Places'),
        ),
        migrations.AddField(
            model_name='community',
            name='team',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='team', to='insight.Team'),
        ),
    ]
