# Generated by Django 3.0.8 on 2020-09-05 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0022_auto_20200904_0859'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='notification',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 9, 6)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 18, 32, 43, 239927, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 18, 32, 43, 240071, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 18, 32, 43, 253872, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 18, 32, 43, 259232, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 18, 32, 43, 259135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 9, 6)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 9, 6)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 18, 32, 43, 241659, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 18, 32, 43, 235587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='date_field',
            field=models.DateField(default=datetime.date(2020, 9, 6)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='time_field',
            field=models.TimeField(default=datetime.time(0, 2, 43, 248255)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 18, 32, 43, 245805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 18, 32, 43, 250366, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractionref',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 9, 6)),
        ),
        migrations.AlterField(
            model_name='useractionref',
            name='time_created',
            field=models.TimeField(default=datetime.time(0, 2, 43, 237543)),
        ),
    ]
