# Generated by Django 3.0.8 on 2020-09-12 15:25

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0023_auto_20200905_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date(2020, 9, 12))),
                ('expires_on', models.DateField(default=datetime.date(2020, 9, 12))),
                ('hobby_scores', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('net_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='community',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='places',
        ),
        migrations.RemoveField(
            model_name='team',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='team',
            name='head',
        ),
        migrations.RemoveField(
            model_name='team',
            name='moderators',
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 9, 12)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 15, 25, 10, 516796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 15, 25, 10, 516929, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 9, 12)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 9, 12)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 15, 25, 10, 518518, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 15, 25, 10, 512544, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='date_field',
            field=models.DateField(default=datetime.date(2020, 9, 12)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='time_field',
            field=models.TimeField(default=datetime.time(20, 55, 10, 525103)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 15, 25, 10, 522705, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractionref',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 9, 12)),
        ),
        migrations.AlterField(
            model_name='useractionref',
            name='time_created',
            field=models.TimeField(default=datetime.time(20, 55, 10, 514539)),
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
