# Generated by Django 3.0.8 on 2020-10-09 17:06

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0027_auto_20200928_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.CharField(default='', max_length=26, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('hobbies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None)),
                ('image', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 10, 9, 17, 6, 46, 180316, tzinfo=utc))),
            ],
        ),

        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='account_id', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='joined_at',
            field=models.DateField(default=datetime.date(2020, 10, 9)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='loved_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 17, 6, 46, 165508, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actionstore',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 17, 6, 46, 165636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 10, 9)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 10, 9)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 17, 6, 46, 167432, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 17, 6, 46, 163454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_activity_on',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 17, 6, 46, 162904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='date_field',
            field=models.DateField(default=datetime.date(2020, 10, 9)),
        ),
        migrations.AlterField(
            model_name='rankbadge',
            name='time_field',
            field=models.TimeField(default=datetime.time(22, 36, 46, 173015)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 10, 9)),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='expires_on',
            field=models.DateField(default=datetime.date(2020, 10, 9)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 17, 6, 46, 170571, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tags',
            name='first_used',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='userpostcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 17, 6, 46, 174970, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=datetime.datetime(2020, 10, 9, 17, 6, 46, 178387, tzinfo=utc))),
                ('position', models.TextField()),
                ('description', models.TextField()),
                ('is_head', models.BooleanField(default=False)),
                ('community_id', models.CharField(max_length=26)),
                ('account', models.ForeignKey(default='account_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 10, 9, 17, 6, 46, 181392, tzinfo=utc))),
                ('is_team_member', models.BooleanField(default=False)),
                ('is_team_head', models.BooleanField(default=False)),
                ('account', models.ForeignKey(default='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='community', to='insight.Community')),
            ],
        ),
    ]
