
# POSTGRES DB
DATABASE_POSTGRES_ENGINE: str = 'django.contrib.gis.db.backends.postgis'
DATABASE_MONGO_ENGINE: str = 'djongo'

DATABASE_POSTGRES_NAME: str = 'insightdb'
DATABASE_MONGO_NAME: str = 'insightdb'

DATABASE_POSTGRES_HOST: str = 'localhost'
DATABASE_POSTGRES_USER: str = 'postgres'
DATABASE_POSTGRES_PASSWORD: str = 'piyush@103'
DATABASE_POSTGRES_PORT: str = '5432'

# CASSANDRA DB FUTURE USE
DATABASE_CASSANDRA_ENGINE: str = 'django_cassandra_engine'
DATABASE_CASSANDRA_NAME: str = ''
DATABASE_CASSANDRA_HOST: str = 'localhost'


DATBASE = {
    'default': {
        'ENGINE': DATABASE_POSTGRES_ENGINE,
        'NAME': DATABASE_POSTGRES_NAME,
        'HOST': DATABASE_CASSANDRA_HOST,
        'PORT': DATABASE_POSTGRES_PORT,
        'USER': DATABASE_POSTGRES_USER,
        'PASSWORD': DATABASE_POSTGRES_PASSWORD
    }
}

