DATABASE_POSTGRES_NAME: str = ''
DATABASE_CASSANDRA_NAME: str = ''
DATABASE_POSTGRES_ENGINE: str = 'django.contrib.gis.db.backends.postgis'
DATABASE_CASSANDRA_ENGINE: str = 'django_cassandra_engine'
DATABASE_POSTGRES_HOST: str = '5432'
DATABASE_CASSANDRA_HOST: str = ''
DATABASE_POSTGRES_USER: str = 'postgres'
DATABASE_POSTGRES_PASSWORD: str = ''

